### ISSUE TITLE
NameError: name 'pyzot' is not defined

### ISSUE THREAD

**Issue by Superraptor** [dlindem/zotwb#5]
Hello! I'm attempting to load from Zotero into a Wikibase.Cloud instance and I've run into the following full-stack:

```
(py311) PS D:\Work\proof_of_concept\wikiodk\zotwb> python3 -m zotwb
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
(py311) PS D:\Work\proof_of_concept\wikiodk\zotwb> python -m zotwb
**** Zotero API key not configured in profile, zotero bot cannot be loaded. ****
Will load profile lgbtdb_1a for Wikibase https://lgbtdb.wikibase.cloud/w/api.php...
lgbtdb_1a: Profile configuration could not be done due to missing values in config.json file in profile folder.       
unsupported operand type(s) for +: 'NoneType' and 'str'
**** Wikibase bot username and password accepted, xwbi can be loaded. ****
xwbi wikibase bot function load finished.
zotwb functions imported.
 * Serving Flask app 'zotwb' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
**** Zotero API key not configured in profile, zotero bot cannot be loaded. ****
Will load profile lgbtdb_1a for Wikibase https://lgbtdb.wikibase.cloud/w/api.php...
lgbtdb_1a: Profile configuration could not be done due to missing values in config.json file in profile folder.       
unsupported operand type(s) for +: 'NoneType' and 'str'
**** Wikibase bot username and password accepted, xwbi can be loaded. ****
xwbi wikibase bot function load finished.
zotwb functions imported.
 * Debugger is active!
 * Debugger PIN: 796-633-912
127.0.0.1 - - [23/Sep/2024 22:23:12] "GET /zotero_export HTTP/1.1" 200 -
127.0.0.1 - - [23/Sep/2024 22:23:13] "GET /static/zotwb_logo.png HTTP/1.1" 304 -
127.0.0.1 - - [23/Sep/2024 22:23:13] "GET /static/favicon.ico HTTP/1.1" 304 -
127.0.0.1 - - [23/Sep/2024 22:23:16] "POST /zotero_export HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\user1\anaconda3\envs\py311\Lib\site-packages\flask\app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\anaconda3\envs\py311\Lib\site-packages\flask\app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\anaconda3\envs\py311\Lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\anaconda3\envs\py311\Lib\site-packages\flask\app.py", line 1525, in full_dispatch_request      
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\anaconda3\envs\py311\Lib\site-packages\flask\app.py", line 1523, in full_dispatch_request      
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\anaconda3\envs\py311\Lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\proof_of_concept\wikiodk\zotwb\zotwb.py", line 113, in zotero_export
    zoterodata = zotwb_functions.zoterobot.getexport(save_to_file=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\proof_of_concept\wikiodk\zotwb\bots\zoterobot.py", line 30, in getexport        
    rawitems = pyzot.everything(pyzot.items(tag=tag))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'pyzot' is not defined
127.0.0.1 - - [23/Sep/2024 22:23:16] "GET /zotero_export?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -    
127.0.0.1 - - [23/Sep/2024 22:23:16] "GET /zotero_export?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -  
127.0.0.1 - - [23/Sep/2024 22:23:16] "GET /zotero_export?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [23/Sep/2024 22:23:16] "GET /zotero_export?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
```

I can't seem to find a `pyzot` package online or via pip or pip3. Everything is installed in an Anaconda environment/virtual environment. But the host system is a Windows system which may be causing the issue?

The server seems to be running fine at `http://127.0.0.1:5000/` and no errors show on the front-end until I try to initiate a `Get records from Zotero` task. Any thoughts or advice much appreciated! Thanks so much!

**Comment by Superraptor** [comment]
Not sure why it closed, re-opening!

**Comment by langflogit** [comment]
I have exactly the same error at the same moment, did you manage to pass around it ?

**Comment by Superraptor** [comment]
@langflogit no unfortunately :(
